version: '3'
services:
  dev:
    command: sleep infinity
    build:
      context: .
    volumes:
      - ..:/workspace
      - ~/.ssh:/root/.ssh
      - ~/.gnupg:/root/.gnupg
      - ~/.gitconfig:/root/.gitconfig
    privileged: true
    ports:
      - "3000:3000"
